services:
  cmd_line_app:
    build: .
    container_name: cmdline-controller
    restart: always
    privileged: true
    stdin_open: true # Keep stdin open
    tty: true # Allocate a pseudo-TTY

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    restart: always

volumes:
  portainer_data:
